name: Hlidac Uredni Desky

on:
  schedule:
    - cron: '0 6,10,15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stáhnout kód
        uses: actions/checkout@v3

      - name: Nastavit Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Nainstalovat knihovny
        run: pip install -r requirements.txt

      - name: Spustit skript
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python bot.py

      - name: Uložit paměť
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posledni_dokumenty.json || exit 0
          git commit -m "Aktualizace paměti bota" || exit 0
          git push
